name: Format (prettier)

on:
  push:
    branches:
      - 'master'
  pull_request:
    paths:
      - '**.css'
      - '**.js'
      - '**.vue'

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2

      - name: Install
        run: yarn install
        env:
          CI: true

      - name: Run pretier
        run: yarn run prettier --write .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.4.1
        with:
          commit_message: Apply Prettier changes
          branch: ${{ github.head_ref }}
          push_options: '--force'
          skip_dirty_check: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}